### ISSUE TITLE
ReviewComponent 수정하기

### ISSUE THREAD

**Issue by jeongyebin** [kookmin-sw/capstone-2020-21#145]
- [x] : 메뉴 제목 변경
- [x] : 모바일 정렬 수정
- [x] : b-calendar -> b-form-datepicker 변경
- [x] : b-time -> b-form-timepicker 변경
- [x] : 만족도 기본값 설정
- [x] : clothes_sets_id 값이 제대로 안온 경우 예외처리
- [x] : clothes_sets_id 값 props로 받기

**Comment by mskwon1** [comment]
메뉴 제목: review 말고 코디리뷰 뭐 이런식으로

모바일 정렬이 안돼있음 ReviewComponent에 cols가 7로 설정돼있는게 문제인듯, 이게 큰 화면에서는 적당한 사이즈로 잘 나오는데 작아지면 뭉개짐
-> cols = "12" md="7" 이런식으로 브레이크포인트별로 컬럼 사이즈를 설정해주는 방법이 있음

활동시간(달력이랑 시간)을 시작/끝별로 같이 보여주는게 좋을 것 같음, 달력은 b-calendar 대신 b-form-datepicker, 시간은 b-time 대신 b-form-timepicker를 사용하는 것이 어떤지

만족도의 경우 건드리지 않고 그냥 등록하기 누를 경우 값이 0으로 넘겨져서 사용자는 3이라 생각하고 넘겼는데 오류가 남. 기본값을 설정해주는게 좋을듯

ReviewComponent가 mount 됐을 때, 코디 id가 안넘겨졌을 경우 alert 띄우고, 이전 페이지로 돌아가는 등의 예외처리 필요

views/Review 파일에 clothes_sets_id 수동으로 입력하게 해놓은거 없애고, Review 파일에서 props 전달받아서 이걸 ReviewComponent한테 전달해주는 방식으로 짜야됨, router.js에서 props 받을 수 있도록 설정해줘야됨(ClosetDetail 참고)
